Blog/myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("post/<str:post_id>", views.detail, name="detail"),
    path("New_url", views.new_url_view, name="new_url_page"),
    path("old_url", views.old_url_redirect, name="old_url"),
]

Blog/myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include



handler404 = 'myapp.views.custom_page_not_found'

urlpatterns = [
    path("Blog/", include("blog.urls")),
    path('admin/', admin.site.urls),
]

Blog/myapp/blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    image_url = models.URLField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=100, default="uncategorized")

    def __str__(self):
        return self.title

Blog/myapp/blog/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from .models import Post
import logging


    # f Data
# posts = [
#         {'id':1, 'title': 'Post 1', 'content': 'Content of Post 1', 'category': 'Sports'},
#         {'id':2, 'title': 'Post 2', 'content': 'Content of Post 2', 'category': 'Science'},
#         {'id':3, 'title': 'Post 3', 'content': 'Content of Post 3', 'category': 'Politics'},
#         {'id':4, 'title': 'Post 4', 'content': 'Content of Post 4', 'category': 'Geography'},
#         {'id':5, 'title': 'Post 5', 'content': 'Content of Post 5', 'category': 'Film Industry'},
#         {'id':6, 'title': 'Post 6', 'content': 'Content of Post 6', 'category': 'Education'},
#     ]



# Create your views here.
def index(request):
    blog_title = "Blog Post"
    blog_head = "My Blog"
    posts = Post.objects.all()
    return render(request, 'blog/index.html', {'blog_title':blog_title, "blog_head":blog_head, 'posts' : posts})

def detail(request, post_id):
    # Post = next((item for item in posts if item['id'] == int(post_id)), None)
    # logger = logging.getLogger("Testing")
    # logger.debug(f'post variable is {Post}')

    try:
        post = Post.objects.get(pk=post_id)   
    except Post.DoesNotExist():
        raise Http404('Sorry, Post Does not exit')
    
    return render(request, 'blog/detail.html', {'post':post})

def old_url_redirect(request):
    return redirect(reverse('blog:new_url_page'))

def new_url_view(request):
    return HttpResponse("<h2>This is new URL</h2>")

Blog/myapp/myapp/views.py
from django.shortcuts import render



def custom_page_not_found(request, exception):
    return render(request,'404.html', status=404)

Blog/myapp/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog_head |default:"Document"}}</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
    <link rel="icon" href="media/icons8-blogger-100.png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="bg-info">

    <!-- Header -->
    {% include 'blog/includes/header.html' %}

    <!-- Dynamic Content -->
    {% block content %}
    {% endblock %}

    <!-- Footer -->

    {% include 'blog/includes/footer.html' %}


<!-- ---------------------------------------------------------------- -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

Blog/myapp/blog/templates/blog/detail.html
{% extends 'blog\base.html' %}

    {% block content %}
    <!-- <head>
        <title>{{Post_title}}</title>
    </head> -->
    <style>
        .custom-bg{
            background-color: #cccccc;
            min-height: 100vh;
        }
        .PostInfo{
            padding: 0 5%;
        }
    </style>

    <section class="PostInfo custom-bg">  
            <div class="row">
                <div class="col-12 col-lg-8 col-sm-12">
                    <div class="container m-4">
                        <div class="card">
                            <div class="row">
                                <div class="col m-4">
                                    <h1 class="">{{ post.title | upper}}</h1>
                                    <p class="text-muted">Posted on {{ post.created_at|date:"F j, Y"}} </p>
                                </div>
                            </div>
                        
                                <div class="col">
                                <div class="card-body">
                                    <img src={{ post.image_url }} class="img-fluid mb-4" alt="Blog Image">
                                    <p> {{ post.content }} </p>
                                </div>
                                </div>                        
                        </div>
                    </div>
                </div>
                    
                <div class="col-12 col-lg-4 col-sm-12">
                    <div class="container m-4">
                        <div class="row">
                            <div class="col">
                                <div class="card">
                                    <div class="card-title">
                                        <h1 class="px-2">Similar Posts</h1>
                                    </div>
                                    <div class="card-body">
                                        <ul>
                                            <li><a class="text-decoration-none" href={% url "blog:index" %}><b>Post 1</b></a></li>
                                            <li><a class="text-decoration-none" href=""><b>Post 2</b></a></li>
                                            <li><a class="text-decoration-none" href=""><b>Post 3</b></a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>  
                    </div>
                </div>

            </div>

    </section>

    {% endblock %}

Blog/myapp/blog/templates/blog/includes/footer.html
<footer class="bg-dark">
            <hr>
            <div class="row">
                <div class="col">
                    <p class="text-info">2025 My Blog. &nbsp;All Rights reserved</p>
                </div>
                <div class="col-12 col-md-6 d-flex justify-content-start justify-content-md-end">
                    <ul class="list-inline">
                        <li class="list-inline-item"><a class="text-white text-decoration-none" href="#">Terms of services</a></li>
                        <li class="list-inline-item"><a class="text-white text-decoration-none" href="#">Privacy policy</a></li>
                        <li class="list-inline-item"><a class="text-white text-decoration-none" href="#">Sitemap</a></li>
                    </ul>
                </div>
            </div>
    </footer>

Blog/myapp/blog/templates/blog/includes/header.html
<header class="bg-dark sticky-top">
        <div class="row">
            <div class="col-12 col-md-6">
                <h1 class="text-info">My Blog</h1>
            </div>
            <div class="col-12 col-md-6 mt-3 d-flex justify-content-start justify-content-md-end">
                <nav>
                    <ul class="list-inline">
                        <li class="list-inline-item "><a class="text-white text-decoration-none" href="#Home">Home</a></li>
                        <li class="list-inline-item "><a class="text-white text-decoration-none" href="#About">About</a></li>
                        <li class="list-inline-item"><a class="text-white text-decoration-none" href="#form">Contact</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>

Blog/myapp/blog/templates/blog/index.html
{% extends 'blog\base.html' %}

    {% block content %}

    <section class="post" id="Home">
        <div class="container py-3">
            <div class="card newbg text-white">
                <div class="card-body">
                    <h1 class="card-title pb-2">Hello Word, Welcome Blog</h1>
                    <h5 class="card-text text-warning">A beginner-friendly blog template designed to help you learn and share your thoughts online.</h5>
                </div>
            </div>
            <div class="row bg-blue-200 mt-2 mb-3">
                <h2 class="text-dark fw-bold" >Latest Posts</h2>
                {% if posts %}
                    {% for post in posts %}
                        <div class="col-12 col-sm-6 col-md-4 col-lg-3 my-2 box">
                            <div class="card">
                                <div class="row">
                                    <div class="col-6 col-sm-12">
                                        <img style="height:300, width:200" class="{{ post.image_url }}" src="https://picsum.photos/id/1/300/200" alt="">
                                    </div>
                                    <div class="col-6 col-sm-12">
                                        <div class="card-body">
                                            <h4 class="card-title mb-2"> {{post.title | truncatechars:30}} </h4>
                                            <p class="card-text"> {{post.content | truncatechars:15}} </p>
                                            <div class="d-flex justify-content-between">
                                                <a class="link_color" href="{% url 'blog:detail' post_id=post.id %}">Read More..</a>
                                                <a class="text-dark fw-bold" href="#"> {{ post.category }} </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor%}
                {% else %}
                    <center><h3 class="fw-b">No Posts available</h3></center>
                {% endif %}
                
            </div>
    
        </div>
    </section>
    <section class="about_us my-3" id="About">
        <div class="container ">
            <div class="row">
                <div class="col-12 p-2 card">
                    <div class="card-body">
                        <div class="card-title">
                            <h1><b>Welcome to SimpleBlog</b></h1>
                            <h2 class="card-subtitle">A space where ideas, stories, and knowledge come together</h2>
                        </div>
                        <div class="card-text">
                            <h4>Our platform is built with a clean and responsive HTML, CSS, and Bootstrap frontend, ensuring that every post looks great on any device. Behind the scenes, we use the power of Python Django to manage content efficiently, while SQLite keeps our data organized, secure, and lightning-fast.</h4>
                            <h4>You're here to read insightful articles, share your thoughts, or explore new perspectives, we've designed this blog to be simple, intuitive, and enjoyable. Every feature is crafted with clarity and accessibility in mind, so you can focus on what matters most — the content.</h4> 
                            <h4>At SimpleBlog, we believe that great ideas deserve a great platform. That's why we combine modern web design with reliable backend technology to give you a smooth, distraction-free reading experience.</h4>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </section>
    <section class="form" id="form">
        <div class="container">
            <div class="row ms-1  ">
                <div class="col-12 col-lg-6 bg-warning p-3">
                    <h3>Contact Form</h3>
                    <form action="">
                        <div class="form-group m-3"> 
                            <label for=""><b>Email Address : </b></label>
                            <input type="email" name="" class="form-control">
                        </div>
                        <div class="form-group m-3">
                            <label for=""><b>Name : </b></label>
                            <input type="text" name="" class="form-control">
                        </div>
                        <div class="form-group m-3">
                            <label for=""><b>Comments : </b></label>
                            <textarea name="" class="form-control" cols="10"></textarea>
                        </div>
                        <button class="btn btn-danger m-3">Submit</button>
                        <button class="btn btn-danger m-3">Cancel</button>
                </form>
                </div>
            </div>
        </div>
    </section>

    {% endblock %}